# Generated by Django 5.2 on 2025-05-21 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_cateogoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=80)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_categoria', to='producto.producto_cateogoria')),
            ],
        ),
    ]
