# Generated by Django 5.2 on 2025-05-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('es_admin', models.BooleanField(default=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
